# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './View/main_window/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CheckBox = CheckBox(self.centralwidget)
        self.CheckBox.setGeometry(QtCore.QRect(220, 60, 92, 22))
        self.CheckBox.setObjectName("CheckBox")
        self.RadioButton = RadioButton(self.centralwidget)
        self.RadioButton.setGeometry(QtCore.QRect(220, 110, 113, 24))
        self.RadioButton.setObjectName("RadioButton")
        self.SwitchButton = SwitchButton(self.centralwidget)
        self.SwitchButton.setGeometry(QtCore.QRect(230, 150, 75, 37))
        self.SwitchButton.setObjectName("SwitchButton")
        self.IconWidget = IconWidget(self.centralwidget)
        self.IconWidget.setGeometry(QtCore.QRect(460, 120, 111, 91))
        self.IconWidget.setObjectName("IconWidget")
        self.ToolButton = ToolButton(self.centralwidget)
        self.ToolButton.setGeometry(QtCore.QRect(240, 350, 91, 51))
        self.ToolButton.setObjectName("ToolButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CheckBox.setText(_translate("MainWindow", "选择"))
        self.RadioButton.setText(_translate("MainWindow", "测试"))
from qfluentwidgets import CheckBox, IconWidget, RadioButton, SwitchButton, ToolButton


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
