# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './View/update/check_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CheckUpdate(object):
    def setupUi(self, CheckUpdate):
        CheckUpdate.setObjectName("CheckUpdate")
        CheckUpdate.resize(395, 294)
        self.gridLayout = QtWidgets.QGridLayout(CheckUpdate)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.version_num = QtWidgets.QLabel(CheckUpdate)
        self.version_num.setText("")
        self.version_num.setObjectName("version_num")
        self.verticalLayout.addWidget(self.version_num)
        self.textBrowser = QtWidgets.QTextBrowser(CheckUpdate)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.autoupdate = QtWidgets.QCheckBox(CheckUpdate)
        self.autoupdate.setObjectName("autoupdate")
        self.horizontalLayout.addWidget(self.autoupdate)
        self.progress = QtWidgets.QProgressBar(CheckUpdate)
        self.progress.setProperty("value", 0)
        self.progress.setObjectName("progress")
        self.horizontalLayout.addWidget(self.progress)
        self.ok = QtWidgets.QPushButton(CheckUpdate)
        self.ok.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ok.setObjectName("ok")
        self.horizontalLayout.addWidget(self.ok)
        self.cancel = QtWidgets.QPushButton(CheckUpdate)
        self.cancel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(CheckUpdate)
        QtCore.QMetaObject.connectSlotsByName(CheckUpdate)

    def retranslateUi(self, CheckUpdate):
        _translate = QtCore.QCoreApplication.translate
        CheckUpdate.setWindowTitle(_translate("CheckUpdate", "检查更新"))
        self.autoupdate.setText(_translate("CheckUpdate", "自动更新"))
        self.ok.setText(_translate("CheckUpdate", "立刻更新"))
        self.cancel.setText(_translate("CheckUpdate", "以后再说"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CheckUpdate = QtWidgets.QDialog()
    ui = Ui_CheckUpdate()
    ui.setupUi(CheckUpdate)
    CheckUpdate.show()
    sys.exit(app.exec_())
