# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './View/page02/page02.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Page02Test(object):
    def setupUi(self, Page02Test):
        Page02Test.setObjectName("Page02Test")
        Page02Test.resize(963, 713)
        Page02Test.setAutoFillBackground(False)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Page02Test)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(7, 7, 7, 7)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.videostream = PixmapLabel(Page02Test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videostream.sizePolicy().hasHeightForWidth())
        self.videostream.setSizePolicy(sizePolicy)
        self.videostream.setScaledContents(True)
        self.videostream.setObjectName("videostream")
        self.verticalLayout.addWidget(self.videostream)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Page02Test)
        QtCore.QMetaObject.connectSlotsByName(Page02Test)

    def retranslateUi(self, Page02Test):
        _translate = QtCore.QCoreApplication.translate
        Page02Test.setWindowTitle(_translate("Page02Test", "Form"))
from qfluentwidgets import PixmapLabel


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Page02Test = QtWidgets.QWidget()
    ui = Ui_Page02Test()
    ui.setupUi(Page02Test)
    Page02Test.show()
    sys.exit(app.exec_())
