# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './View/page02/page02.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Page02Test(object):
    def setupUi(self, Page02Test):
        Page02Test.setObjectName("Page02Test")
        Page02Test.resize(963, 713)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Page02Test)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.videostream = PixmapLabel(Page02Test)
        self.videostream.setObjectName("videostream")
        self.gridLayout.addWidget(self.videostream, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Page02Test)
        QtCore.QMetaObject.connectSlotsByName(Page02Test)

    def retranslateUi(self, Page02Test):
        _translate = QtCore.QCoreApplication.translate
        Page02Test.setWindowTitle(_translate("Page02Test", "Form"))
from qfluentwidgets import PixmapLabel


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Page02Test = QtWidgets.QWidget()
    ui = Ui_Page02Test()
    ui.setupUi(Page02Test)
    Page02Test.show()
    sys.exit(app.exec_())
